window.GARVEE_DEMO_DATA = {
  "snapshotDate": "2026-09-23",
  "sourceUrl": "https://www.garvee.com/collections/new-arrivals?filter.v.availability=true",
  "dataNote": "Product names, images, prices, availability and visible review data come from Garvee's public page snapshot. Sales velocity, category revenue and fallback launch age are deterministic demo metrics.",
  "categorySales": {
    "Agriculture & Forestry": 129782,
    "Lawn & Garden": 134708,
    "Home & Furniture": 183117,
    "Rugs": 47790,
    "Automotive": 175052,
    "Air Conditioners": 340635,
    "Restaurant & Food Service": 54844,
    "Toys & Games": 0,
    "Sports & Outdoors": 16631
  },
  "products": [
    {
      "id": "garvee-drag-harrow-driveway-grader-heavy-pho-15eyvdv5",
      "handle": "garvee-drag-harrow-driveway-grader-heavy-pho-15eyvdv5",
      "name": "Garvee 6 FT Drag Harrow Driveway Grader, Heavy Duty Power Rake, Driveway Drag for Gravel W/ 6 FT Chain, Tow Behind Lawn Rake for ATV, UTV, Tractor, Mower, Land Leveler for Gravel, Sand, Soil, Hay",
      "url": "https://www.garvee.com/products/garvee-drag-harrow-driveway-grader-heavy-pho-15eyvdv5",
      "category": "Agriculture & Forestry",
      "subcategory": "Equipment Parts & Accessories",
      "price": 123.99,
      "compareAt": 189.99,
      "rating": 4.84,
      "reviews": 167,
      "inventory": 52,
      "addedDays": 9,
      "addedIsDemo": true,
      "sold30": 19,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-01.webp"
    },
    {
      "id": "garvee-2-pack-12-inch-hanging-ppg-35vgrnux",
      "handle": "garvee-2-pack-12-inch-hanging-ppg-35vgrnux",
      "name": "Garvee 2 Pack 12 Inch Hanging Basket with Removable Water Reservoir, Plastic Self Watering Planters, Hanging Plant Pot for Window Porch Garden Balcony,White",
      "url": "https://www.garvee.com/products/garvee-2-pack-12-inch-hanging-ppg-35vgrnux",
      "category": "Lawn & Garden",
      "subcategory": "Garden Supplies",
      "price": 54.99,
      "compareAt": 64.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 91,
      "addedDays": 6,
      "addedIsDemo": false,
      "sold30": 200,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-02.webp"
    },
    {
      "id": "garvee-heavy-duty-dog-crate-with-sliding-barn-door-black-pps-335vcozq",
      "handle": "garvee-heavy-duty-dog-crate-with-sliding-barn-door-black-pps-335vcozq",
      "name": "Garvee Heavy Duty Wooden Dog Crate Furniture with Sliding Barn Door and 2 Storage Drawers, Indoor Dog Kennel End Table with Hook, Farmhouse Style Dog Crates for Medium/Large Dogs, Black",
      "url": "https://www.garvee.com/products/garvee-heavy-duty-dog-crate-with-sliding-barn-door-black-pps-335vcozq",
      "category": "Home & Furniture",
      "subcategory": "Pet Supplies",
      "price": 205.99,
      "compareAt": 299.99,
      "rating": 4.79,
      "reviews": 14,
      "inventory": 257,
      "addedDays": 14,
      "addedIsDemo": true,
      "sold30": 194,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-03.webp"
    },
    {
      "id": "garvee-4x6-botanical-scalloped-area-rug-phk-36h3bk6f",
      "handle": "garvee-4x6-botanical-scalloped-area-rug-phk-36h3bk6f",
      "name": "Garvee 4' × 6' Scalloped Area Rug, Washable Non-Slip Low-Pile Botanical Rug for Living Room, Bedroom & Dining Room, Blue",
      "url": "https://www.garvee.com/products/garvee-4x6-botanical-scalloped-area-rug-phk-36h3bk6f",
      "category": "Rugs",
      "subcategory": "Area Rugs",
      "price": 26.99,
      "compareAt": 39.99,
      "rating": 4.8,
      "reviews": 64,
      "inventory": 13,
      "addedDays": 8,
      "addedIsDemo": false,
      "sold30": 167,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-04.webp"
    },
    {
      "id": "garvee-heavy-duty-steel-truck-bed-pae-33l6bxx6",
      "handle": "garvee-heavy-duty-steel-truck-bed-pae-33l6bxx6",
      "name": "Garvee 30\"x13\"x9.6\" Heavy-Duty Steel Truck Bed Tool Box, Lockable Weather-Resistant Storage Chest for Pickup, RV, and Trailer, Black with Silver Floral",
      "url": "https://www.garvee.com/products/garvee-heavy-duty-steel-truck-bed-pae-33l6bxx6",
      "category": "Automotive",
      "subcategory": "Automotive Accessories",
      "price": 150.99,
      "compareAt": 215.99,
      "rating": 4.85,
      "reviews": 114,
      "inventory": 81,
      "addedDays": 28,
      "addedIsDemo": false,
      "sold30": 120,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-05.webp"
    },
    {
      "id": "garvee-24000-btu-21-seer2-ductless-mhk-375k4len",
      "handle": "garvee-24000-btu-21-seer2-ductless-mhk-375k4len",
      "name": "Garvee 24000 BTU 21 SEER2 Ductless Mini Split AC & Heat Pump WiFi Alexa Compatible 208-230V Energy-Star Efficient Cooling Heating for 1500 Sq.ft",
      "url": "https://www.garvee.com/products/garvee-24000-btu-21-seer2-ductless-mhk-375k4len",
      "category": "Air Conditioners",
      "subcategory": "Mini Split Air Conditioners",
      "price": 1135.99,
      "compareAt": 1499.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 51,
      "addedDays": 17,
      "addedIsDemo": true,
      "sold30": 91,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-06.webp"
    },
    {
      "id": "garvee-utility-sink-large-stainless-steel-laundry-room-pls_33at9ukl",
      "handle": "garvee-utility-sink-large-stainless-steel-laundry-room-pls_33at9ukl",
      "name": "Garvee Stainless Steel Utility Sink Large Freestanding Laundry Sink with Hot/Cold Faucet for Garage Kitchen Bathroom Laundry Room Black",
      "url": "https://www.garvee.com/products/garvee-utility-sink-large-stainless-steel-laundry-room-pls_33at9ukl",
      "category": "Restaurant & Food Service",
      "subcategory": "Restaurant Faucets & Plumbing & Sinks",
      "price": 227.99,
      "compareAt": 227.99,
      "rating": 4.98,
      "reviews": 92,
      "inventory": 22,
      "addedDays": 12,
      "addedIsDemo": true,
      "sold30": 141,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-07.webp"
    },
    {
      "id": "garvee-portable-lightweight-transport-wheelchair-with-phh-335bulvm",
      "handle": "garvee-portable-lightweight-transport-wheelchair-with-phh-335bulvm",
      "name": "Garvee 28.66lbs Lightweight Transport Wheelchair - 12\" PU Rear Wheels Foldable Travel Wheel Chair with Flip-Back Armrests, Jet Black",
      "url": "https://www.garvee.com/products/garvee-portable-lightweight-transport-wheelchair-with-phh-335bulvm",
      "category": "Sports & Outdoors",
      "subcategory": "Action Aids",
      "price": 215.99,
      "compareAt": 236.99,
      "rating": 5.0,
      "reviews": 15,
      "inventory": 10,
      "addedDays": 14,
      "addedIsDemo": true,
      "sold30": 77,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-08.webp"
    },
    {
      "id": "garvee-46-5-cant-hook-log-lifter-32-log-pls-33y7ylnx",
      "handle": "garvee-46-5-cant-hook-log-lifter-32-log-pls-33y7ylnx",
      "name": "Garvee 46.5\" Cant Hook Log Roller and Lifter, Carbon Steel Timberjack for Logs up to 32\" Diameter, Orange",
      "url": "https://www.garvee.com/products/garvee-46-5-cant-hook-log-lifter-32-log-pls-33y7ylnx",
      "category": "Agriculture & Forestry",
      "subcategory": "Equipment Parts & Accessories",
      "price": 68.99,
      "compareAt": 81.99,
      "rating": 5.0,
      "reviews": 2,
      "inventory": 39,
      "addedDays": 22,
      "addedIsDemo": false,
      "sold30": 51,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-09.webp"
    },
    {
      "id": "garvee-2-pack-12-inch-hanging-ppg-35vgdfvk",
      "handle": "garvee-2-pack-12-inch-hanging-ppg-35vgdfvk",
      "name": "Garvee 2 Pack 12 Inch Hanging Basket with Removable Water Reservoir, Plastic Self Watering Planters, Hanging Plant Pot for Window Porch Garden Balcony,Green",
      "url": "https://www.garvee.com/products/garvee-2-pack-12-inch-hanging-ppg-35vgdfvk",
      "category": "Lawn & Garden",
      "subcategory": "Garden Supplies",
      "price": 54.99,
      "compareAt": 64.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 81,
      "addedDays": 6,
      "addedIsDemo": false,
      "sold30": 127,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-10.webp"
    },
    {
      "id": "garvee-31-5-in-dog-crate-furniture-with-lock-arched-door-pps-33j83h7s",
      "handle": "garvee-31-5-in-dog-crate-furniture-with-lock-arched-door-pps-33j83h7s",
      "name": "Garvee Dog Crate Furniture, 31.5\" Indoor Dog Kennel with Lock & Arched Door, Reinforced Metal Frame as End Table for Small Dogs, Black + Walnut",
      "url": "https://www.garvee.com/products/garvee-31-5-in-dog-crate-furniture-with-lock-arched-door-pps-33j83h7s",
      "category": "Home & Furniture",
      "subcategory": "Pet Supplies",
      "price": 119.99,
      "compareAt": 208.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 110,
      "addedDays": 15,
      "addedIsDemo": false,
      "sold30": 153,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-11.webp"
    },
    {
      "id": "garvee-forest-botanical-area-rug-9x12-green-phk-369s68lo",
      "handle": "garvee-forest-botanical-area-rug-9x12-green-phk-369s68lo",
      "name": "Garvee 9' x 12' Vintage Forest Botanical Area Rug, Deep Green Washable Soft Low-Pile Non-Slip Rug for Living Room, Bedroom & Dining Room",
      "url": "https://www.garvee.com/products/garvee-forest-botanical-area-rug-9x12-green-phk-369s68lo",
      "category": "Rugs",
      "subcategory": "Area Rugs",
      "price": 79.99,
      "compareAt": 109.99,
      "rating": 4.89,
      "reviews": 63,
      "inventory": 17,
      "addedDays": 12,
      "addedIsDemo": false,
      "sold30": 125,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-12.webp"
    },
    {
      "id": "garvee-heavy-duty-steel-truck-bed-pae-33l6zv79",
      "handle": "garvee-heavy-duty-steel-truck-bed-pae-33l6zv79",
      "name": "Garvee 48\"X15\"X15\" Heavy-Duty Steel Truck Bed Tool Box, Lockable Weather-Resistant Storage Chest for Pickup/RV/Trailer, Black Background with Silver Flowers",
      "url": "https://www.garvee.com/products/garvee-heavy-duty-steel-truck-bed-pae-33l6zv79",
      "category": "Automotive",
      "subcategory": "Automotive Accessories",
      "price": 321.99,
      "compareAt": 459.99,
      "rating": 4.85,
      "reviews": 114,
      "inventory": 57,
      "addedDays": 28,
      "addedIsDemo": false,
      "sold30": 42,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-13.webp"
    },
    {
      "id": "garvee-mini-split-ac-heat-pump-mhk-375f38rq",
      "handle": "garvee-mini-split-ac-heat-pump-mhk-375f38rq",
      "name": "Garvee Mini Split AC & Heat Pump 18000 BTU 19 SEER2 WiFi Smart Control R32 Refrigerant Ultra-Quiet Cooling Heating for 1250 Sq.ft Homes",
      "url": "https://www.garvee.com/products/garvee-mini-split-ac-heat-pump-mhk-375f38rq",
      "category": "Air Conditioners",
      "subcategory": "Mini Split Air Conditioners",
      "price": 746.99,
      "compareAt": 899.99,
      "rating": 4.84,
      "reviews": 147,
      "inventory": 345,
      "addedDays": 53,
      "addedIsDemo": true,
      "sold30": 109,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-14.webp"
    },
    {
      "id": "garvee-utility-sink-large-stainless-steel-laundry-phs_33atbqxb",
      "handle": "garvee-utility-sink-large-stainless-steel-laundry-phs_33atbqxb",
      "name": "Garvee Stainless Steel Utility Sink Large Freestanding Laundry Sink with Hot/Cold Faucet for Garage Kitchen Bathroom Laundry Room Black",
      "url": "https://www.garvee.com/products/garvee-utility-sink-large-stainless-steel-laundry-phs_33atbqxb",
      "category": "Restaurant & Food Service",
      "subcategory": "Restaurant Faucets & Plumbing & Sinks",
      "price": 290.99,
      "compareAt": 290.99,
      "rating": 4.98,
      "reviews": 92,
      "inventory": 8,
      "addedDays": 84,
      "addedIsDemo": true,
      "sold30": 78,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-15.webp"
    },
    {
      "id": "garvee-48-timberjack-log-lifter-15-log-ppg-35u63m8g",
      "handle": "garvee-48-timberjack-log-lifter-15-log-ppg-35u63m8g",
      "name": "Garvee 48\" Log Lifter with Adjustable Cant Hook, Carbon Steel Timberjack for Logs up to 15\" Diameter, Orange",
      "url": "https://www.garvee.com/products/garvee-48-timberjack-log-lifter-15-log-ppg-35u63m8g",
      "category": "Agriculture & Forestry",
      "subcategory": "Equipment Parts & Accessories",
      "price": 75.99,
      "compareAt": 89.99,
      "rating": 5.0,
      "reviews": 1,
      "inventory": 84,
      "addedDays": 22,
      "addedIsDemo": false,
      "sold30": 21,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-16.webp"
    },
    {
      "id": "garvee-130-lbs-tow-behind-broadcast-ppg-3547s4a6",
      "handle": "garvee-130-lbs-tow-behind-broadcast-ppg-3547s4a6",
      "name": "Garvee 130 lbs Tow-Behind Broadcast Spreader, Lawn & Garden Fertilizer Seeder with 10\" Pneumatic Tires, Adjustable Flow Control, Waterproof Cover & Sieve for Seed, Salt, Ice Melt & Sand",
      "url": "https://www.garvee.com/products/garvee-130-lbs-tow-behind-broadcast-ppg-3547s4a6",
      "category": "Lawn & Garden",
      "subcategory": "Garden Supplies",
      "price": 171.99,
      "compareAt": 169.99,
      "rating": 4.57,
      "reviews": 23,
      "inventory": 169,
      "addedDays": 8,
      "addedIsDemo": true,
      "sold30": 202,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-17.webp"
    },
    {
      "id": "garvee-18-in-1-wall-mounted-cat-shelves-set-beige-phk-3b88e7cf",
      "handle": "garvee-18-in-1-wall-mounted-cat-shelves-set-beige-phk-3b88e7cf",
      "name": "Garvee 18-in-1 Wall-Mounted Cat Shelves Set – Beige Climbing Perch, Steps & Play Bridge for Indoor Cats – Beige",
      "url": "https://www.garvee.com/products/garvee-18-in-1-wall-mounted-cat-shelves-set-beige-phk-3b88e7cf",
      "category": "Home & Furniture",
      "subcategory": "Pet Supplies",
      "price": 149.99,
      "compareAt": 239.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 106,
      "addedDays": 15,
      "addedIsDemo": false,
      "sold30": 22,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-18.webp"
    },
    {
      "id": "garvee-scalloped-floral-area-rug-5x7-grass-green-phk-36epa7kh",
      "handle": "garvee-scalloped-floral-area-rug-5x7-grass-green-phk-36epa7kh",
      "name": "Garvee 5' x 7' Green Scalloped Floral Area Rug, Washable Non-Slip Low-Pile Botanical Bordered Rug for Living Room, Bedroom, Dining Room & Office",
      "url": "https://www.garvee.com/products/garvee-scalloped-floral-area-rug-5x7-grass-green-phk-36epa7kh",
      "category": "Rugs",
      "subcategory": "Area Rugs",
      "price": 42.99,
      "compareAt": 59.99,
      "rating": 4.9,
      "reviews": 41,
      "inventory": 12,
      "addedDays": 12,
      "addedIsDemo": false,
      "sold30": 45,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-19.webp"
    },
    {
      "id": "garvee-heavy-duty-steel-truck-bed-pae-33l60x2o",
      "handle": "garvee-heavy-duty-steel-truck-bed-pae-33l60x2o",
      "name": "Garvee 20\"X12\"X9.6\" Heavy-Duty Steel Truck Bed Tool Box, Lockable Weather-Resistant Storage Chest for Pickup/RV/Trailer, Black Background with Silver Flowers",
      "url": "https://www.garvee.com/products/garvee-heavy-duty-steel-truck-bed-pae-33l60x2o",
      "category": "Automotive",
      "subcategory": "Automotive Accessories",
      "price": 125.99,
      "compareAt": 179.99,
      "rating": 4.85,
      "reviews": 114,
      "inventory": 56,
      "addedDays": 28,
      "addedIsDemo": false,
      "sold30": 220,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-20.webp"
    },
    {
      "id": "garvee-24000-btu-high-efficiency-mini-mhk-375gubeb",
      "handle": "garvee-24000-btu-high-efficiency-mini-mhk-375gubeb",
      "name": "Garvee 24000 BTU High Efficiency Mini Split Central Air Conditioner & Heater – 19 SEER2, 230V, WiFi Enabled, Ductless AC System for Home, US Standard",
      "url": "https://www.garvee.com/products/garvee-24000-btu-high-efficiency-mini-mhk-375gubeb",
      "category": "Air Conditioners",
      "subcategory": "Mini Split Air Conditioners",
      "price": 973.99,
      "compareAt": 2110.99,
      "rating": 4.84,
      "reviews": 147,
      "inventory": 42,
      "addedDays": 80,
      "addedIsDemo": true,
      "sold30": 160,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-21.webp"
    },
    {
      "id": "garvee-10-compartment-chicken-nesting-box-with-legs-red-pps-33a8dvrp",
      "handle": "garvee-10-compartment-chicken-nesting-box-with-legs-red-pps-33a8dvrp",
      "name": "Garvee 10-Compartment Roll Away Chicken Nesting Box with Legs, Galvanized Steel Poultry Nest for Easy Egg Collection, Red",
      "url": "https://www.garvee.com/products/garvee-10-compartment-chicken-nesting-box-with-legs-red-pps-33a8dvrp",
      "category": "Agriculture & Forestry",
      "subcategory": "Livestock & Poultry Supplies",
      "price": 223.99,
      "compareAt": 263.99,
      "rating": 4.73,
      "reviews": 11,
      "inventory": 119,
      "addedDays": 26,
      "addedIsDemo": false,
      "sold30": 83,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-22.webp"
    },
    {
      "id": "garvee-self-watering-tall-planter-pots-ppg-34nnsbl6",
      "handle": "garvee-self-watering-tall-planter-pots-ppg-34nnsbl6",
      "name": "Garvee Self-Watering Tall Planter Pots, 2-Pack - 16 in Large Weather-Resistant Plastic with Water Level Gauge & Removable Inner Pot - Black, Direct Plastic Style",
      "url": "https://www.garvee.com/products/garvee-self-watering-tall-planter-pots-ppg-34nnsbl6",
      "category": "Lawn & Garden",
      "subcategory": "Garden Supplies",
      "price": 52.99,
      "compareAt": 96.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 395,
      "addedDays": 15,
      "addedIsDemo": false,
      "sold30": 242,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-23.webp"
    },
    {
      "id": "garvee-extra-large-90-walk-in-wooden-outdoor-catio-enclosure-mps-33dlkls4",
      "handle": "garvee-extra-large-90-walk-in-wooden-outdoor-catio-enclosure-mps-33dlkls4",
      "name": "Garvee Extra Large 90\" Walk-in Wooden Outdoor Catio Enclosure for Multiple Cats - UV-Proof Cover with 2 Side Doors - Gray",
      "url": "https://www.garvee.com/products/garvee-extra-large-90-walk-in-wooden-outdoor-catio-enclosure-mps-33dlkls4",
      "category": "Home & Furniture",
      "subcategory": "Pet Supplies",
      "price": 399.99,
      "compareAt": 674.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 67,
      "addedDays": 23,
      "addedIsDemo": false,
      "sold30": 209,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-24.webp"
    },
    {
      "id": "garvee-cat-themed-scalloped-rug-2x6-brown-phk-3cxtdy96",
      "handle": "garvee-cat-themed-scalloped-rug-2x6-brown-phk-3cxtdy96",
      "name": "Garvee 2' × 6' Cat-Themed Scalloped Runner Rug, Machine Washable Non-Slip Low-Pile Soft Rug for Hallway, Kitchen & Entryway, Brown",
      "url": "https://www.garvee.com/products/garvee-cat-themed-scalloped-rug-2x6-brown-phk-3cxtdy96",
      "category": "Rugs",
      "subcategory": "Area Rugs",
      "price": 19.99,
      "compareAt": 29.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 22,
      "addedDays": 12,
      "addedIsDemo": false,
      "sold30": 92,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-25.webp"
    },
    {
      "id": "garvee-heavy-duty-truck-bed-tool-pae-34e3cnpx",
      "handle": "garvee-heavy-duty-truck-bed-tool-pae-34e3cnpx",
      "name": "Garvee 48\"x15\"x15\" Heavy-Duty Steel Truck Bed Tool Box, 110° Gas-Strut Assisted Opening, Scratch-Resistant Textured Matte Finish, Lockable Weather-Resistant Storage for Pickup & Trailer, Black",
      "url": "https://www.garvee.com/products/garvee-heavy-duty-truck-bed-tool-pae-34e3cnpx",
      "category": "Automotive",
      "subcategory": "Automotive Accessories",
      "price": 319.99,
      "compareAt": 458.99,
      "rating": 4.86,
      "reviews": 85,
      "inventory": 72,
      "addedDays": 28,
      "addedIsDemo": false,
      "sold30": 18,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-26.webp"
    },
    {
      "id": "garvee-10-compartment-roll-away-chicken-nesting-box-green-pps-33a838t0",
      "handle": "garvee-10-compartment-roll-away-chicken-nesting-box-green-pps-33a838t0",
      "name": "Garvee 10-Compartment Roll Away Chicken Nesting Box, Galvanized Steel Wall Mount Poultry Nest for Easy Egg Collection, Green",
      "url": "https://www.garvee.com/products/garvee-10-compartment-roll-away-chicken-nesting-box-green-pps-33a838t0",
      "category": "Agriculture & Forestry",
      "subcategory": "Livestock & Poultry Supplies",
      "price": 226.99,
      "compareAt": 267.99,
      "rating": 4.73,
      "reviews": 11,
      "inventory": 10,
      "addedDays": 26,
      "addedIsDemo": false,
      "sold30": 139,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-27.webp"
    },
    {
      "id": "garvee-48-adjustable-artificial-grass-rake-ppg-36lqyqas",
      "handle": "garvee-48-adjustable-artificial-grass-rake-ppg-36lqyqas",
      "name": "Garvee 48\" Adjustable Artificial Grass Rake, Outdoor Lawn Broom with Metal Handle, Multipurpose Garden Brush for Leaves & Pet Hair",
      "url": "https://www.garvee.com/products/garvee-48-adjustable-artificial-grass-rake-ppg-36lqyqas",
      "category": "Lawn & Garden",
      "subcategory": "Garden Supplies",
      "price": 36.99,
      "compareAt": 62.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 50,
      "addedDays": 15,
      "addedIsDemo": false,
      "sold30": 69,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-28.webp"
    },
    {
      "id": "garvee-heavy-duty-4-hook-bird-feeder-pole-metal-stand-black-ppg-35hcbtn8",
      "handle": "garvee-heavy-duty-4-hook-bird-feeder-pole-metal-stand-black-ppg-35hcbtn8",
      "name": "Garvee Heavy Duty 4-Hook Bird Feeder Pole – Adjustable 92-Inch Black Metal Stand – Squirrel Proof, Reinforced Ground Base, Detachable Tray & Bird Bath – 25mm Stable Outdoor Feeding Station, Size: 92inch",
      "url": "https://www.garvee.com/products/garvee-heavy-duty-4-hook-bird-feeder-pole-metal-stand-black-ppg-35hcbtn8",
      "category": "Home & Furniture",
      "subcategory": "Pet Supplies",
      "price": 49.99,
      "compareAt": 57.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 57,
      "addedDays": 25,
      "addedIsDemo": false,
      "sold30": 108,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-29.webp"
    },
    {
      "id": "garvee-braided-print-rug-modern-boho-2x4-black-pho-104gnvmz",
      "handle": "garvee-braided-print-rug-modern-boho-2x4-black-pho-104gnvmz",
      "name": "Garvee 2' × 4' Braided Print Runner Rug, Machine Washable Non-Slip Low-Pile Boho Rug for Hallway, Kitchen & Entryway, Black",
      "url": "https://www.garvee.com/products/garvee-braided-print-rug-modern-boho-2x4-black-pho-104gnvmz",
      "category": "Rugs",
      "subcategory": "Area Rugs",
      "price": 29.99,
      "compareAt": 39.99,
      "rating": 4.71,
      "reviews": 80,
      "inventory": 6,
      "addedDays": 22,
      "addedIsDemo": false,
      "sold30": 153,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-30.webp"
    },
    {
      "id": "garvee-heavy-duty-truck-bed-tool-pae-34e3ead7",
      "handle": "garvee-heavy-duty-truck-bed-tool-pae-34e3ead7",
      "name": "Garvee 42\"x15\"x15\" Heavy-Duty Steel Truck Bed Tool Box - 110° Gas-Strut Assisted Opening, Scratch-Resistant Textured Matte Finish, Lockable Weather-Resistant Storage for Pickup & Trailer, Black",
      "url": "https://www.garvee.com/products/garvee-heavy-duty-truck-bed-tool-pae-34e3ead7",
      "category": "Automotive",
      "subcategory": "Automotive Accessories",
      "price": 304.99,
      "compareAt": 435.99,
      "rating": 4.86,
      "reviews": 85,
      "inventory": 70,
      "addedDays": 28,
      "addedIsDemo": false,
      "sold30": 52,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-31.webp"
    },
    {
      "id": "garvee-8-compartment-roll-away-chicken-nesting-box-blue-pps-33a8fhsu",
      "handle": "garvee-8-compartment-roll-away-chicken-nesting-box-blue-pps-33a8fhsu",
      "name": "Garvee 8-Compartment Roll Away Chicken Nesting Box, Galvanized Steel Wall Mount Poultry Nest for Easy Egg Collection, Blue",
      "url": "https://www.garvee.com/products/garvee-8-compartment-roll-away-chicken-nesting-box-blue-pps-33a8fhsu",
      "category": "Agriculture & Forestry",
      "subcategory": "Livestock & Poultry Supplies",
      "price": 153.99,
      "compareAt": 181.99,
      "rating": 4.73,
      "reviews": 11,
      "inventory": 1,
      "addedDays": 26,
      "addedIsDemo": false,
      "sold30": 203,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-32.webp"
    },
    {
      "id": "garveeextra-wide-9x15-patio-umbrella-ppg-34wwxk5d",
      "handle": "garveeextra-wide-9x15-patio-umbrella-ppg-34wwxk5d",
      "name": "Garvee 9' × 15' Rectangular Patio Umbrella with Base, 98% UV-Blocking Oxford Canopy, 12-Rib Metal Frame, Gray",
      "url": "https://www.garvee.com/products/garveeextra-wide-9x15-patio-umbrella-ppg-34wwxk5d",
      "category": "Lawn & Garden",
      "subcategory": "Outdoor Shade",
      "price": 139.99,
      "compareAt": 179.99,
      "rating": 4.62,
      "reviews": 8,
      "inventory": 247,
      "addedDays": 19,
      "addedIsDemo": true,
      "sold30": 144,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-33.webp"
    },
    {
      "id": "garvee-heavy-duty-40-50-gallon-aquarium-stand-with-2-tier-storage-black-phk-38qhgc9v",
      "handle": "garvee-heavy-duty-40-50-gallon-aquarium-stand-with-2-tier-storage-black-phk-38qhgc9v",
      "name": "Garvee Heavy-Duty 40-50 Gallon Aquarium Stand with 2-Tier Storage Cabinet for Fish, Turtle & Reptile Tanks – Rustic Brown Wood & Metal Design, Adjustable Feet, Black",
      "url": "https://www.garvee.com/products/garvee-heavy-duty-40-50-gallon-aquarium-stand-with-2-tier-storage-black-phk-38qhgc9v",
      "category": "Home & Furniture",
      "subcategory": "Pet Supplies",
      "price": 166.99,
      "compareAt": 196.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 37,
      "addedDays": 25,
      "addedIsDemo": false,
      "sold30": 52,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-34.webp"
    },
    {
      "id": "garvee-outdoor-patio-rug-waterproof-reversible-9x12-black-brown-ppg-3636nnu5",
      "handle": "garvee-outdoor-patio-rug-waterproof-reversible-9x12-black-brown-ppg-3636nnu5",
      "name": "Garvee 9' × 12' Reversible Outdoor Patio Rug, Waterproof Foldable Plastic Straw Mat for Patio, Deck, RV & Camping, Black/Brown",
      "url": "https://www.garvee.com/products/garvee-outdoor-patio-rug-waterproof-reversible-9x12-black-brown-ppg-3636nnu5",
      "category": "Rugs",
      "subcategory": "Area Rugs",
      "price": 64.99,
      "compareAt": 89.99,
      "rating": 4.67,
      "reviews": 9,
      "inventory": 73,
      "addedDays": 22,
      "addedIsDemo": false,
      "sold30": 167,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-35.webp"
    },
    {
      "id": "garvee-30-inch-steel-truck-bed-pae-34ejpuc8",
      "handle": "garvee-30-inch-steel-truck-bed-pae-34ejpuc8",
      "name": "Garvee 30\"X16\"X14\" Heavy-Duty Steel Truck Bed Tool Box, Lockable Storage Chest with Front Handles, Gas Struts, and Weather-Resistant Design for Pickup Beds, Black",
      "url": "https://www.garvee.com/products/garvee-30-inch-steel-truck-bed-pae-34ejpuc8",
      "category": "Automotive",
      "subcategory": "Automotive Accessories",
      "price": 217.99,
      "compareAt": 319.99,
      "rating": 4.89,
      "reviews": 47,
      "inventory": 19,
      "addedDays": 28,
      "addedIsDemo": false,
      "sold30": 34,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-36.webp"
    },
    {
      "id": "garvee-6-ft-steel-u-post-fence-stakes-20-pack-black-ppg-3644dflu",
      "handle": "garvee-6-ft-steel-u-post-fence-stakes-20-pack-black-ppg-3644dflu",
      "name": "Garvee 6 ft Heavy Duty No Dig Steel U Post Fence Stakes, 20 Pack Metal Fence Posts with Anchors and Clips, Black",
      "url": "https://www.garvee.com/products/garvee-6-ft-steel-u-post-fence-stakes-20-pack-black-ppg-3644dflu",
      "category": "Agriculture & Forestry",
      "subcategory": "Livestock & Poultry Supplies",
      "price": 129.99,
      "compareAt": 152.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 99,
      "addedDays": 26,
      "addedIsDemo": false,
      "sold30": 159,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-37.webp"
    },
    {
      "id": "garvee-heavy-duty-garden-cart-wagon-pho-34h8e0qw",
      "handle": "garvee-heavy-duty-garden-cart-wagon-pho-34h8e0qw",
      "name": "Garvee Heavy Duty Garden Cart Wagon with 10\" Pneumatic Tires & Removable Mesh Sides ， Wagon for Yard, Garden, Hauling, All Terrain Outdoor Use",
      "url": "https://www.garvee.com/products/garvee-heavy-duty-garden-cart-wagon-pho-34h8e0qw",
      "category": "Lawn & Garden",
      "subcategory": "Garden Supplies",
      "price": 109.99,
      "compareAt": 164.99,
      "rating": 4.86,
      "reviews": 195,
      "inventory": 263,
      "addedDays": 22,
      "addedIsDemo": false,
      "sold30": 188,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-38.webp"
    },
    {
      "id": "garvee-3-tier-heavy-duty-10-gallon-aquarium-stand-with-storage-shelves-phk-38qe6yjr",
      "handle": "garvee-3-tier-heavy-duty-10-gallon-aquarium-stand-with-storage-shelves-phk-38qe6yjr",
      "name": "Garvee Heavy Duty 10 Gallon Aquarium Stand with Storage Shelves – 3-Tier Metal & Wood Fish Tank Stand, Holds Up to 220 lbs, Adjustable Leveling Feet, Brown",
      "url": "https://www.garvee.com/products/garvee-3-tier-heavy-duty-10-gallon-aquarium-stand-with-storage-shelves-phk-38qe6yjr",
      "category": "Home & Furniture",
      "subcategory": "Pet Supplies",
      "price": 59.99,
      "compareAt": 111.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 99,
      "addedDays": 25,
      "addedIsDemo": false,
      "sold30": 122,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-39.webp"
    },
    {
      "id": "garvee-gothic-cat-rug-floral-boho-8x10-black-brown-phk-3awcjm33",
      "handle": "garvee-gothic-cat-rug-floral-boho-8x10-black-brown-phk-3awcjm33",
      "name": "Garvee 8' × 10' Gothic Cat Area Rug, Machine Washable Non-Slip Low-Pile Floral Boho Rug for Living Room, Bedroom & Entryway, Black/Brown",
      "url": "https://www.garvee.com/products/garvee-gothic-cat-rug-floral-boho-8x10-black-brown-phk-3awcjm33",
      "category": "Rugs",
      "subcategory": "Area Rugs",
      "price": 76.99,
      "compareAt": 109.99,
      "rating": 5.0,
      "reviews": 5,
      "inventory": 21,
      "addedDays": 22,
      "addedIsDemo": false,
      "sold30": 126,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-40.webp"
    },
    {
      "id": "garvee-36-inch-steel-truck-bed-pae-34ejjp55",
      "handle": "garvee-36-inch-steel-truck-bed-pae-34ejjp55",
      "name": "Garvee 36\"X16\"X14\" Heavy-Duty Steel Truck Bed Tool Box, Lockable Storage Chest with Front Handles, Gas Struts, and Weather-Resistant Design for Pickup Beds, Black/Silk Flowers",
      "url": "https://www.garvee.com/products/garvee-36-inch-steel-truck-bed-pae-34ejjp55",
      "category": "Automotive",
      "subcategory": "Automotive Accessories",
      "price": 275.99,
      "compareAt": 395.99,
      "rating": 4.89,
      "reviews": 47,
      "inventory": 33,
      "addedDays": 28,
      "addedIsDemo": false,
      "sold30": 75,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-41.webp"
    },
    {
      "id": "garvee-6-ft-steel-u-post-fence-stakes-20-pack-green-ppg-36449vl3",
      "handle": "garvee-6-ft-steel-u-post-fence-stakes-20-pack-green-ppg-36449vl3",
      "name": "Garvee 6 ft Heavy Duty No Dig Steel U Post Fence Stakes, 20 Pack Metal Fence Posts with Anchors and Clips, Green",
      "url": "https://www.garvee.com/products/garvee-6-ft-steel-u-post-fence-stakes-20-pack-green-ppg-36449vl3",
      "category": "Agriculture & Forestry",
      "subcategory": "Livestock & Poultry Supplies",
      "price": 129.99,
      "compareAt": 152.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 53,
      "addedDays": 26,
      "addedIsDemo": false,
      "sold30": 61,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-42.webp"
    },
    {
      "id": "garvee-heavy-duty-garden-cart-wagon-pho-34h8al7n",
      "handle": "garvee-heavy-duty-garden-cart-wagon-pho-34h8al7n",
      "name": "Garvee Heavy Duty Garden Cart Wagon with 10\" Pneumatic Tires & Removable Mesh Sides ， Wagon for Yard, Garden, Hauling, All Terrain Outdoor Use",
      "url": "https://www.garvee.com/products/garvee-heavy-duty-garden-cart-wagon-pho-34h8al7n",
      "category": "Lawn & Garden",
      "subcategory": "Garden Supplies",
      "price": 99.99,
      "compareAt": 158.99,
      "rating": 4.86,
      "reviews": 195,
      "inventory": 252,
      "addedDays": 22,
      "addedIsDemo": false,
      "sold30": 169,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-43.webp"
    },
    {
      "id": "garvee-heavy-duty-3-tier-aquarium-stand-for-10-gallon-fish-tank-phk-38qkmctt",
      "handle": "garvee-heavy-duty-3-tier-aquarium-stand-for-10-gallon-fish-tank-phk-38qkmctt",
      "name": "Garvee Heavy-Duty 3-Tier Rustic Brown Aquarium Stand for 10 Gallon Fish Tank, Turtle or Reptile Terrarium – Sturdy Metal-Reinforced Wooden Cabinet with Storage Shelves & Adjustable Leveling Feet – Color: Brown",
      "url": "https://www.garvee.com/products/garvee-heavy-duty-3-tier-aquarium-stand-for-10-gallon-fish-tank-phk-38qkmctt",
      "category": "Home & Furniture",
      "subcategory": "Pet Supplies",
      "price": 54.99,
      "compareAt": 99.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 56,
      "addedDays": 25,
      "addedIsDemo": false,
      "sold30": 118,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-44.webp"
    },
    {
      "id": "garvee-gothic-cat-rug-floral-boho-2x6-black-brown-phk-3awcamp9",
      "handle": "garvee-gothic-cat-rug-floral-boho-2x6-black-brown-phk-3awcamp9",
      "name": "Garvee 2' × 6' Gothic Cat Runner Rug, Machine Washable Non-Slip Low-Pile Stain-Resistant Floral Boho Rug for Hallway, Kitchen & Entryway, Black/Brown",
      "url": "https://www.garvee.com/products/garvee-gothic-cat-rug-floral-boho-2x6-black-brown-phk-3awcamp9",
      "category": "Rugs",
      "subcategory": "Area Rugs",
      "price": 22.99,
      "compareAt": 29.99,
      "rating": 5.0,
      "reviews": 5,
      "inventory": 7,
      "addedDays": 22,
      "addedIsDemo": false,
      "sold30": 57,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-45.webp"
    },
    {
      "id": "garvee-36-inch-steel-truck-bed-pae-34ejd6r9",
      "handle": "garvee-36-inch-steel-truck-bed-pae-34ejd6r9",
      "name": "Garvee 36\"X16\"X14\" Heavy-Duty Steel Truck Bed Tool Box, Lockable Storage Chest with Front Handles, Gas Struts, and Weather-Resistant Design for Pickup Beds, Black",
      "url": "https://www.garvee.com/products/garvee-36-inch-steel-truck-bed-pae-34ejd6r9",
      "category": "Automotive",
      "subcategory": "Automotive Accessories",
      "price": 275.99,
      "compareAt": 395.99,
      "rating": 4.89,
      "reviews": 47,
      "inventory": 31,
      "addedDays": 28,
      "addedIsDemo": false,
      "sold30": 239,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-46.webp"
    },
    {
      "id": "garvee-heavy-duty-4000lbs-3-point-ppg-355y86rs",
      "handle": "garvee-heavy-duty-4000lbs-3-point-ppg-355y86rs",
      "name": "Garvee Heavy Duty 4000lbs 3-Point Quick Hitch for Category 2 Tractors - 5-Level Adjustable Bolt - 2\" Receiver - Compatible with Cat 2 Implements - Farm Attachment - Orange",
      "url": "https://www.garvee.com/products/garvee-heavy-duty-4000lbs-3-point-ppg-355y86rs",
      "category": "Agriculture & Forestry",
      "subcategory": "Equipment Parts & Accessories",
      "price": 227.99,
      "compareAt": 271.99,
      "rating": 4.8,
      "reviews": 5,
      "inventory": 14,
      "addedDays": 29,
      "addedIsDemo": true,
      "sold30": 54,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-47.webp"
    },
    {
      "id": "garvee-16-tall-outdoor-planters-set-ppg-367tb96x",
      "handle": "garvee-16-tall-outdoor-planters-set-ppg-367tb96x",
      "name": "Garvee 16\" Tall Outdoor Planters Set of 2 – Large Weather-Resistant Plastic Flower Pots with Drainage for Patio & Garden – Black, 15.7 Inches",
      "url": "https://www.garvee.com/products/garvee-16-tall-outdoor-planters-set-ppg-367tb96x",
      "category": "Lawn & Garden",
      "subcategory": "Garden Supplies",
      "price": 70.99,
      "compareAt": 118.99,
      "rating": 0.0,
      "reviews": 0,
      "inventory": 800,
      "addedDays": 22,
      "addedIsDemo": false,
      "sold30": 125,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-48.webp"
    },
    {
      "id": "garvee-heavy-duty-collapsible-dog-grooming-table-36-in-pink-pps-33mfsd4w",
      "handle": "garvee-heavy-duty-collapsible-dog-grooming-table-36-in-pink-pps-33mfsd4w",
      "name": "Garvee Folding Dog Grooming Table, 36\" Non-Slip Surface, Adjustable Arm & Safety Noose, Mesh Storage Tray, Stable Triangular Frame, 330 lbs Capacity, Pink",
      "url": "https://www.garvee.com/products/garvee-heavy-duty-collapsible-dog-grooming-table-36-in-pink-pps-33mfsd4w",
      "category": "Home & Furniture",
      "subcategory": "Pet Supplies",
      "price": 109.99,
      "compareAt": 185.99,
      "rating": 4.0,
      "reviews": 1,
      "inventory": 47,
      "addedDays": 28,
      "addedIsDemo": false,
      "sold30": 91,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-49.webp"
    },
    {
      "id": "garvee-gothic-cat-rug-floral-boho-2x6-brown-phk-3awc5gks",
      "handle": "garvee-gothic-cat-rug-floral-boho-2x6-brown-phk-3awc5gks",
      "name": "Garvee 2' × 6' Gothic Cat Runner Rug, Machine Washable Non-Slip Low-Pile Stain-Resistant Floral Boho Rug for Hallway, Kitchen & Entryway, Brown",
      "url": "https://www.garvee.com/products/garvee-gothic-cat-rug-floral-boho-2x6-brown-phk-3awc5gks",
      "category": "Rugs",
      "subcategory": "Area Rugs",
      "price": 22.99,
      "compareAt": 29.99,
      "rating": 5.0,
      "reviews": 5,
      "inventory": 31,
      "addedDays": 22,
      "addedIsDemo": false,
      "sold30": 133,
      "delivery": "Sep 26–29",
      "image": "./assets/products/product-50.webp"
    }
  ]
};
